<?php

// src/Support/LearnedTree.php

namespace Ghostwire\Support;

/**
 * Server-side re-validation of the learned-tree envelope produced by
 * Ghostwire.exportLearned() in the browser, plus the static-Blade emitter.
 *
 * The file arrives from a developer's own download directory, so it is treated as
 * untrusted input: every rule the JS store enforces on read is enforced again
 * here (SPEC-SEC-04's integrity rules, SPEC-SEC-05's sanitized numeric
 * dimensions and no learned data interpolated as markup).
 *
 * This mirrors js/src/learning/store.js's validBone()/validEntry()/validEnvelope()
 * independently, by hand - the two cannot share code across the language
 * boundary. Keep the constants and clamps below in sync with that file; it
 * carries a comment pointing back here for the same reason.
 */
final class LearnedTree
{
    public const SCHEMA_VERSION = 1;

    public const MAX_COORD = 20000;

    public const MAX_BONES = 300;

    public const BONE_TYPES = ['text', 'avatar', 'block', 'icon', 'media', 'control', 'heading'];

    public const NAME_PATTERN = '/^[a-z0-9\-.]{1,64}$/';

    /**
     * @return array{width: float, height: float, bones: array<int, array{type: string, x: float, y: float, width: float, height: float}>}|null
     */
    public static function fromJson(string $json, string $component, string $band): ?array
    {
        $parsed = json_decode($json, true);

        if (! is_array($parsed) || ($parsed['v'] ?? null) !== self::SCHEMA_VERSION) {
            return null;
        }

        if (! is_array($parsed['e'] ?? null) || ! is_array($parsed['c'] ?? null)) {
            return null;
        }

        $signature = $parsed['c'][$component.'|'.$band] ?? null;

        if (! is_string($signature) && ! is_int($signature)) {
            return null;
        }

        $entry = $parsed['e'][$signature.'|'.$band] ?? null;

        if (! is_array($entry) || ($entry['n'] ?? null) !== $component) {
            return null;
        }

        if (! is_array($entry['b'] ?? null) || $entry['b'] === [] || count($entry['b']) > self::MAX_BONES) {
            return null;
        }

        $bones = [];

        foreach ($entry['b'] as $bone) {
            $valid = self::validBone($bone);

            if ($valid === null) {
                return null; // one bad bone discards the whole entry
            }

            $bones[] = $valid;
        }

        $width = self::clamp($entry['w'] ?? null, 0, self::MAX_COORD);
        $height = self::clamp($entry['h'] ?? null, 0, self::MAX_COORD);

        if ($width === null || $height === null) {
            return null;
        }

        return ['width' => $width, 'height' => $height, 'bones' => $bones];
    }

    /**
     * @param  array{width: float, height: float, bones: array<int, array<string, mixed>>}  $entry
     */
    public static function toBlade(array $entry): string
    {
        $lines = [
            // Plain HTML comments, not {{-- Blade --}} ones: a Blade comment's own
            // delimiter starts with the literal characters "{{", which is exactly
            // the Blade-echo token SPEC-SEC-05 requires this file to contain zero
            // occurrences of. HTML comments carry no such token and still compile
            // through Blade untouched.
            '<!-- Generated by `php artisan ghost:export`. Static Blade, no dynamic values. -->',
            '<!-- Regenerate rather than editing this by hand. -->',
            sprintf(
                '<div class="gw-lazy" aria-hidden="true" style="position:relative;width:%.2fpx;height:%.2fpx">',
                $entry['width'],
                $entry['height'],
            ),
        ];

        foreach ($entry['bones'] as $bone) {
            $lines[] = sprintf(
                '    <div class="gw-bone gw-bone--%s" style="position:absolute;left:%.2fpx;top:%.2fpx;width:%.2fpx;height:%.2fpx"></div>',
                $bone['type'],   // already restricted to self::BONE_TYPES
                $bone['x'],
                $bone['y'],
                $bone['width'],
                $bone['height'],
            );
        }

        $lines[] = '</div>';

        return implode("\n", $lines)."\n";
    }

    /**
     * @return array{type: string, x: float, y: float, width: float, height: float}|null
     */
    private static function validBone(mixed $bone): ?array
    {
        if (! is_array($bone)) {
            return null;
        }

        $keys = array_keys($bone);
        sort($keys);

        if ($keys !== ['height', 'type', 'width', 'x', 'y']) {
            return null;
        }

        if (! is_string($bone['type']) || ! in_array($bone['type'], self::BONE_TYPES, true)) {
            return null;
        }

        $x = self::clamp($bone['x'], -self::MAX_COORD, self::MAX_COORD);
        $y = self::clamp($bone['y'], -self::MAX_COORD, self::MAX_COORD);
        $width = self::clamp($bone['width'], 0, self::MAX_COORD);
        $height = self::clamp($bone['height'], 0, self::MAX_COORD);

        if ($x === null || $y === null || $width === null || $height === null) {
            return null;
        }

        return ['type' => $bone['type'], 'x' => $x, 'y' => $y, 'width' => $width, 'height' => $height];
    }

    private static function clamp(mixed $value, float $min, float $max): ?float
    {
        if (! is_int($value) && ! is_float($value)) {
            return null;
        }

        if (is_nan((float) $value) || is_infinite((float) $value)) {
            return null;
        }

        return min($max, max($min, (float) $value));
    }
}
